### PR TITLE
Spawn players on their respective sides of the map

### PR DESCRIPTION
**Pull request by JanSGNm**
As LaMqTa suggested, I've edited spawn files to spawn BLU players on BLU side of the map and RED players on RED side.
Additionally, I've added some spawns on cp_sunshine_rc8, cp_granary, cp_granary_pro_b10, gullywash and koth_product_rc8.
Locations of added spawns are noted in commits comments, either in text or picture.

### CODE REVIEW

**Comment by Zeluboba** [comment]
nice job, I hope we'll have spawns for every map after ours commits

**Comment by Lange** [comment]
I'm not sure how I feel about spawning teams on their respective sides of the map. That's a pretty big change that I don't know if people want.

**Comment by JanSGNm** [comment]
Ok, then we leave it like that. For now, all commonly used maps in competitive are included and updated.

**Comment by Zeluboba** [comment]
@Lange if you ask me, I will answer that I like this update as user, because that's not nice when people are waiting you to spawn and kill you behind on your side of the map, lol. That would be nice if you won't be afraid that someone will spawn behind you.

**Comment by LaMqTa** [comment]
I would suggest to add this. I've been hearing about people getting confused because they are being spawned on random places on the maps. I personally don't have any problem with the spawns but seems that the new players are getting confused. I will defenitely add this to my TDM servers and will let you know if there is any negative feedback about it.

**Comment by Zeluboba** [comment]
@Lange merge? As user on @LaMqTa servers I like this update.

**Comment by Lange** [comment]
I am of the opinion that this functionality should be optional via a cvar. The default value of this cvar should be the current behavior, and if server operators wish to have this new behavior they can change the value of this cvar.

I'm closing this pull request, but will happily review a new PR with the above change.

**Pull request closed without merging**
