### PR TITLE
Add options to disable health and ammo packs

### PR DESCRIPTION
**Pull request by RisingFog**
~~Marking this as WIP as I have not had the chance to get this tested out, and marked as RFC as I'm not sure if this is something that SOAP should be doing natively.~~

The plugin file has already been re-compiled.

### CODE REVIEW

**Comment by Lange** [comment]
I'm not necessarily against including this functionality. As someone who has had to set up many servers in my time with the game, I know that it's pretty tedious and reducing the number of plugins that one has to install and keep updated is nice.

Let me know once you've had time to test this out and how those tests went.

**Comment by Lange** [comment]
I should also mention that if SourcePawn/SourceMod were more ergonomic, I'd absolutely want this broken out into a separate, tiny module. That's how it'd do it in any modern language these days. But, we gotta be pragmatic, accept the limitations of the system, and try to deliver the best experience for users with the tools available.

**Comment by RisingFog** [comment]
I got someone to test it for me, and both the health packs and ammo packs disappeared.

This should be okay to merge.

**Comment by Lange** [comment]
Just to be safe, has it also been verified that health & ammo packs properly remain when `soap_disablehealthpacks` and `soap_disableammopacks` are set to `0`?

**Comment by RisingFog** [comment]
They remain when they're set to 0.

**Pull request merged**
