### PR TITLE
Fix check that prevents people form spawning inside each other

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes the trace hull arguments so it does the collision check properly

### CODE REVIEW

**Comment by icewind1991** [comment]
I'm not sure what to do about the the compiled version of the plugin? just commit the updated binary?

**Comment by Lange** [comment]
Can you explain what exactly is fixed by this change? To my knowledge, the current code does its job correctly even if I may have messed up the arguments.

**Comment by icewind1991** [comment]
Hmm, you're right, after retesting the check currently works as expected.

I was confused by the spawns on steel, which because you spawn in the air, it allows people to spawn on each other after a player falls down.

Maybe in combination with the ceiling spawn on steel it caused people to spawn inside each other.

**Comment by icewind1991** [comment]
probably still makes sense to merge this pr though

**Pull request merged**
