### PR TITLE
Added support for mp_tournament_readymode.

### PR DESCRIPTION
**Pull request by averagecomputerguy**

### CODE REVIEW

**Comment by mr64bit** [comment]
Darn, you beat me to it.

What's the reason behind removing the "mp_tournament_readymode" functionality? Was there any hard conflict with the new system? If not, then even though it's not used much, it's still a feature that shouldn't be removed for no reason. 

Also, before this is merged, you'll need to commit the compiled .smx file. Most people just download the .zip file from Github and just extract it into their SourceMod folder, so the repo needs to include an updated .smx file.

**Comment by averagecomputerguy** [comment]
Thanks mr64bit. Forgot about adding the compiled version to the repo.

As far as I could tell, Event_TournamentEnableCountdown was only there to unload soap_tf2dm when everyone had readied up in mp_tournament_readymode, but soap_tf2dm wasn't getting unloaded when this happened.

**Comment by Lange** [comment]
I'm not sure what exactly this changes. What is being added and removed here?

**Comment by averagecomputerguy** [comment]
Previously there was a HookEvent for tournament_enablecountdown for unloading SOAP DM once everyone had readied up in mp_tournament_readymode. That HookEvent didn't get triggered for mp_tournament_readymode, so I removed it.

soap_tournament now pushes a client's userid to their appropriate team's array (redPlayersReady/bluePlayersReady) once they ready up with tournament_player_readystate 1. When a player unreadies or changes their team, their userid is removed from their team's array. When both team's arrays are equal to the value of mp_tournament_readymode_min, StopDeathmatching() is called because the game is starting.

Both of the team arrays are cleared when StartDeathmatching() or StopDeathmatching() is called because if mp_tournament_readymode wasn't turned on before a map change, clients think that they can ready up. The userids put in the team arrays would be carried over with the map change if the arrays weren't cleared in StartDeathmatching().

**Comment by Lange** [comment]
Okay. And this change is necessary because the way that teams ready up is different now? When soap_tournament was written, per-player ready-up didn't exist. The old interface was to have the entire team ready up. Is that old system still around? Does your change prevent soap_tournament from working with that old system?

**Comment by averagecomputerguy** [comment]
The old system is still around. I just tested soap_tournament with the new and old systems again and it works with both.

**Comment by Lange** [comment]
Okay, sounds good to me. Thanks!

**Pull request merged**
